### ISSUE TITLE
white space after field:

### ISSUE THREAD

**Issue by matthiasg** [mahnunchik/lucene-query-parser#4]
I am trying to find out whether the lucene query string syntax allows whitespace between field name and term. lucene-query-parser does not allow whitespace right now. The docs don't explicitly forbid it just mention the field is followed by the term. 

Example:
```
field: value 
```

Raises: `expected "+", "-" or whitespace but "v" found`. And requires:

```
field:value
```

Elasticsearches query_string parser does allow it and thus I would like to understand what the behavior should be or whether this parser should be updated.

**Comment by mahnunchik** [comment]
I'm sorry, but I do not maintain this library. It seems original author too 😞

**Comment by matthiasg** [comment]
@mahnunchik yeah I realized that too. Thanks.
